### ISSUE TITLE
ddraw.ini settings

### ISSUE THREAD

**Issue by FunkyFr3sh** [senpaisomething/PD2Launcher#3]
Bugs:
Max Game Ticks combobox doesn't have the default "-2" setting

Suggestions:
Remove "Stretch cutscenes to fullscreen" setting since it doesn't work for diablo 2 (It's a setting specific to cnc games)
Move "Automatic mouse sensitivity" out of Advanced Options and list it on top at DDraw Options instead

**Comment by Elmegaard** [comment]
No longer using ddraw.ini
